### ISSUE TITLE
Segmentation violation when running in xorg

### ISSUE THREAD

**Issue by aded** [remogatto/mandala#5]
Hi dude!
Sometimes I catch the following seg fault, after creating an app and playing with worlds, boxes, etc. It happens when I close the window.

(From inside an app generated via mandala-template):

$ gotask run xorg
OK          Build the application for the given platforms.
libEGL warning: failed to create a pipe screen for i915
SIGSEGV: segmentation violation
PC=0xb30492c0
signal arrived during cgo execution

runtime.cgocall(0x804f920, 0xb7653eec)
    /home/aded/var/src/go/src/pkg/runtime/cgocall.c:149 +0x10c fp=0xb7653ee0
github.com/remogatto/opengles2._Cfunc_glClear(0x4000)
    github.com/remogatto/opengles2/_obj/_cgo_defun.c:200 +0x31 fp=0xb7653eec
github.com/remogatto/opengles2.Clear(0x4000)
    /home/aded/dev/go/src/github.com/remogatto/opengles2/opengles2.go:148 +0x28 fp=0xb7653ef4
main.(_gameState).draw(0x18645080)
    /home/aded/dev/go/src/aded.it/myapp/src/myapp/game.go:214 +0x28 fp=0xb7653f00
main.func·001(0xb7714850, 0x1861c210, 0x0, 0x0)
    /home/aded/dev/go/src/aded.it/myapp/src/myapp/game.go:289 +0x171 fp=0xb7653f24
git.tideland.biz/goas/loop.func·002()
    /home/aded/dev/go/src/git.tideland.biz/goas/loop/loop.go:186 +0x93 fp=0xb7653f90
git.tideland.biz/goas/loop.(_loop).recoverableLoop(0x1861c210)
    /home/aded/dev/go/src/git.tideland.biz/goas/loop/loop.go:198 +0xb2 fp=0xb7653fc4
runtime.goexit()
    /home/aded/var/src/go/src/pkg/runtime/proc.c:1394 fp=0xb7653fc8
created by git.tideland.biz/goas/loop.GoRecoverable
    /home/aded/dev/go/src/git.tideland.biz/goas/loop/loop.go:160 +0xba

goroutine 1 [syscall]:
github.com/go-gl/glfw3._Cfunc_glfwTerminate(0x80544b2)
    github.com/go-gl/glfw3/_obj/_cgo_defun.c:843 +0x31
github.com/go-gl/glfw3.Terminate()
    /home/aded/dev/go/src/github.com/go-gl/glfw3/glfw.go:59 +0x1b
main.main()
    /home/aded/dev/go/src/aded.it/myapp/src/myapp/main.go:90 +0x3b2

goroutine 3 [select]:
github.com/remogatto/mandala.func·002(0xb7714850, 0x1861c0f0, 0x0, 0x18640800)
    /home/aded/dev/go/src/github.com/remogatto/mandala/resourcemanager.go:34 +0x191
git.tideland.biz/goas/loop.func·002()
    /home/aded/dev/go/src/git.tideland.biz/goas/loop/loop.go:186 +0x93
git.tideland.biz/goas/loop.(*loop).recoverableLoop(0x1861c0f0)
    /home/aded/dev/go/src/git.tideland.biz/goas/loop/loop.go:198 +0xb2
created by git.tideland.biz/goas/loop.GoRecoverable
    /home/aded/dev/go/src/git.tideland.biz/goas/loop/loop.go:160 +0xba

goroutine 4 [syscall]:
runtime.goexit()
    /home/aded/var/src/go/src/pkg/runtime/proc.c:1394

eax     0x2
ebx     0xb4b48000
ecx     0x1
edx     0xb75dc96c
edi     0x0
esi     0xb755c288
ebp     0x0
esp     0xb5afe25c
eip     0xb30492c0
eflags  0x10246
cs      0x73
fs      0x0
gs      0x33
exit status 2
FAIL        Run the application on the given platforms.
2014/02/12 19:46:29 exit status 1

Bye

**Comment by remogatto** [comment]
I think the issue is related with a wrong termination of the GLFW library. I'll check it ASAP. Thanks for reporting.
